development:
  adapter: postgresql
  encoding: unicode
  database: films_development
  username: film
  password: film
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: films_test
  username: film
  password: film
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: films_production
  username: films_production
  password: imouto
  pool: 5
  timeout: 5000
