development:
  adapter: mysql2
  database: films_development
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: films_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: films_production
  username: films_production
  password: imouto
  pool: 5
  timeout: 5000
